name: crampening
description: Cram your Chess Openings
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.3

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_chess_board:
    git: 
      url: https://github.com/dawid-niedzwiecki/flutter_chess_board.git
      ref: master
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  provider: ^6.0.3

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
